web:
  build: .
  command: /usr/bin/supervisord -n -c /etc/supervisord.conf
  working_dir: /usr/share/nginx/html/
  ports:
    - "8080:80"
  links:
    - db
    - data
  volumes_from:
    - data
  environment:
    ENV_MYSQL_DATABASE: snapdb
    ENV_MYSQL_HOST: db
    ENV_MYSQL_USER: snap
    ENV_MYSQL_PASSWORD: snap
data:
  image: base/arch
  volumes:
    - /var/lib/mysql
    - ./:/usr/share/nginx/html/
  command: true
  privileged: true
db:
  image: mysql:latest
  privileged: true
  volumes_from:
    - data
  ports:
    - "3307:3306"
  environment:
    MYSQL_DATABASE: snapdb
    MYSQL_USER: snap
    MYSQL_PASSWORD: snap
    MYSQL_ROOT_PASSWORD: foobar


